### ISSUE TITLE
Provide a 3D model of the "injection moulded panel"

### ISSUE THREAD

**Issue by DominikPalo** [openKolibri/klais-16#4]
I would like to try to 3D print the covering panel (using two colors - semitransparent and black), but I didn't find the 3D file in the repository (just the screenshot attached below). So, could you please share this design as a STEP or an STL file? Thank you! :) 

![panel](https://github.com/DominikPalo/klais-16/raw/master/docs/assembly/imProto.png)

**Comment by Sawaiz** [comment]
Here ([imProto.zip](https://github.com/openKolibri/klais-16/files/5845870/imProto.zip)) is all the file types that could be useful that I can export. Its not included in the files until I design it in freecad or something that is acessible. I just sliced it and looks reasonable, but for printing you might want to remove a bunch of draft angles and the even wall thickness isn't as improtant.

Would love to see a photo of your print when you do it and to know how it works out!

**Comment by DominikPalo** [comment]
Thank you - I imported the .igs file to my Fusion 360 and it works great, it seems I will bee able to adjust the model for better printing :) Of course, I will share the results with you, but I've just ordered the main PCB from JLPCB (and the TM1640 drivers from China), so it will take a few weeks until I finish and test it (it will be so much fun with those 128pcs of 0603 LEDs - I ordered stencils and will try to assemble it using a solder paste and hot air) :) 

Anyway, thanks for the great and well-documented project - I like the idea!

**Comment by Sawaiz** [comment]
Sounds great. The `.ipt` file would probably import best as that is the source and fusing is also autodesk.

Best of luck, you can reopen the issue if you have progress to share, or just tag `@openkolibri` and/or `@sawaizsyed` on twitter.

**Comment by DominikPalo** [comment]
Yes, I know that `.ipt` would be better, but I'm using Fusion 360 with a free hobby license, which doesn't support importing IPT files (IPT files are supported only in paid license types).. therefore I used (but I will try to find someone who with a paid license who will convert that `.ipt` to `.f3d` so I can see the timeline and features from the original model)
